### ISSUE TITLE
Anzeigefehler bei Verwendung von Security-Header "Content-Security-Policy"

### ISSUE THREAD

**Issue by SpeGal** [duncrow-gmbh/flipbert#10]
Seitdem wir die Content-Security-Policy auf unserer Website verwenden, 
gibt es in allen Flipbooks Anzeigefehler. Schriften und Bilder werden nicht mehr korrekt dargestellt:

<img width="500" alt="Screenshot 2022-12-06 163215" src="https://user-images.githubusercontent.com/3717412/205955597-ca22dcf2-f701-49df-ad81-3eaade280e49.png">

Ohne die CSP funktioniert die Anzeige. Wir möchten aus SIcherheitsgründen die Policy aber natürlich gerne verwenden. Was ist der Grund für den Anzeigefehler?

**Comment by cmartin6** [comment]
Hallo @SpeGal, tut mir leid, dass du so lange auf eine Antwort warten musstest.

Wenn du in der config.yml mit `nelmio_security` die CSP-Einstellungen setzen willst, musst du bitte bei Verwendung von Flipbert folgendes beachten:
- für `img-src` muss `'blob:'` enthalten sein
- für `default-src` empfehlen wir ebenfalls `'blob:'` einzubauen

**Comment by cmartin6** [comment]
@SpeGal funktioniert es nun?

**Comment by SpeGal** [comment]
Leider nicht. Wir hatten die nelmio_security bisher so eingebaut, wie hier beschrieben:
https://github.com/contao/contao/issues/1174

Mit dem Blobs würde es dann so aussehen:
`nelmio_security:
    csp:
        enabled: true
        hash:
            algorithm: sha256
        enforce:
            level1_fallback: false
            img-src:
                - '* data: unsafe-inline'
                - 'blob:'
            default-src:
                - '*'
                - 'unsafe-eval'
                - 'unsafe-inline'
                - 'blob:'
            script-src:
                - '*'
                - 'unsafe-eval'
                - 'unsafe-inline'`

Das Ergebnis ist aber noch dasselbe wie oben. Also mit den kaputten Schriften ... Wir haben die Schriften lokal eingebunden.

**Comment by SpeGal** [comment]
Wir haben die Angaben jetzt testweise so eingestellt und es funktioniert:
`# Security configuration
nelmio_security:
    csp:
        enabled: true
        hash:
            algorithm: sha256
        enforce:
            script-src:
                - 'self'`

Der Sicherheits-Check ergibt, dass die Seite mit A+ eingestuft wird und flipbert funktioniert trotzdem. Oder ist das CSP durch dieses Setting dann nicht mehr so sicher?

**Comment by SpeGal** [comment]
Nach längerem hin und her Probieren funktioniert es bei uns jetzt mit diesen Einstellungen (und hoffentlich einigermaßen sicher):

`# Security configuration
nelmio_security:
    csp:
        enabled: true
        hash:
            algorithm: sha256
        enforce:
            default-src:
                - 'self'
                - 'https://*.youtube.com'
                - 'https://*.googleapis.com'
            img-src:
                - 'self'
                - 'https://*.googleapis.com'
                - 'data:' 
                - 'blob:'
                - 'unsafe-inline'
            script-src:
                - 'self'
                - 'https://*.googleapis.com'
                - 'data:'
                - 'blob:'
                - 'unsafe-eval'
                - 'unsafe-inline'
            font-src:
                - 'self'
                - 'data:'
            style-src:
                - 'self'
                - 'https://*.googleapis.com'
                - 'unsafe-inline'`

**Comment by cmartin6** [comment]
Okay, ich bin leider selber kein Experte was CSP angeht. Aber wenn es jetzt funktioniert, schließe ich das Issue entsprechend.
