### ISSUE TITLE
ALTER TABLE tl_flipbook schlägt fehl

### ISSUE THREAD

**Issue by mlwebworker** [duncrow-gmbh/flipbert#11]
In einer Installation mit der Erweiterung flipbert schlägt 
```
ALTER TABLE tl_flipbook CHANGE alias alias VARCHAR(128) CHARACTER SET utf8 DEFAULT '' NOT NULL COLLATE `utf8_bin`
```
ohne Fehlermeldung fehl.
Die Aktualisierung scheint scheinbar durchzulaufen, wird aber danach wieder als ausstehende Migration angezeigt (getestet mit dem Contao Manger, dem Installtool und auf der Konsole)

Contao: 4.13.26
Flipbert: 1.6.5
PHP: 8.1
MySQL: 10.11.4-MariaDB

Nach Aussage von Andy Schempp auf Slack müsste die Ursache in der Erweiterung liegen (ungültiges SQL definiert). https://contao.slack.com/archives/CK4J0KNDB/p1689247191287969?thread_ts=1689247124.513699&cid=CK4J0KNDB

**Comment by mlwebworker** [comment]
Wie sieht es damit aus? Ich habe die Änderung gerade wieder mal manuell durchgeführt, damit die DB-Änderungen ohne Fehler durchlaufen.

**Comment by ggradwohl** [comment]
Danke für den pull Request, hab ich gemerged
