### ISSUE TITLE
Abhängigkeit zu guzzlehttp/guzzle verhindert Updates anderer Erweiterungen

### ISSUE THREAD

**Issue by ThomasKettner** [duncrow-gmbh/flipbert#13]
Aktuell ist die Abhängigkeit zu guzzle 6.5 eingestellt.
Wäre es möglich, diese auf 7.4 oder höher zu ergänzen?

**Comment by ggradwohl** [comment]
In v 1.7.0 wurde Guzzle auf ^7.4 erweitert.
