### ISSUE TITLE
Title Error

### ISSUE THREAD

**Issue by rburch** [duncrow-gmbh/flipbert#7]
I can't save anything in the module because the Title field won't take anything I input
<img width="1181" alt="title-error" src="https://user-images.githubusercontent.com/1537395/141194329-c6beaa6c-4484-4362-93ac-8e3b03d34d49.png">
.

**Comment by cmartin6** [comment]
Could you please provide some additional information about this error? Which version of flipbert is installed? Did you enter your license key in the settings?

Please try updating the extension via contao-manager first

**Comment by cmartin6** [comment]
Is this still relevant?

**Comment by rburch** [comment]
I honestly don't know because it was a long time ago. I'm sorry. My guess is that if you're not having the issue it's been fixed or had to do with my setup at the time.
