### ISSUE TITLE
"Uncaught PHP Exception TypeError" wenn "Ausgeblendete Icons der Kontrollleiste" leer

### ISSUE THREAD

**Issue by Webstylerin** [duncrow-gmbh/flipbert#8]
Hallo,

der Aufruf der flipberts im Frontend war nicht mehr möglich, da sofort folgender Fehler kam:

`[2022-07-26 12:20:32] request.CRITICAL: Uncaught PHP Exception TypeError: "implode(): Argument #2 ($array) must be of type ?array, bool given" at /html/domain.tld/vendor/duncrow-gmbh/flipbert/src/Resources/contao/templates/frontend/duncrow_flipbook.html5 line 7 {"exception":"[object] (TypeError(code: 0): implode(): Argument #2 ($array) must be of type ?array, bool given at /html/domain.tld/vendor/duncrow-gmbh/flipbert/src/Resources/contao/templates/frontend/duncrow_flipbook.html5:7)"} []`

"Lösen" konnte ich den Fehler, indem ich mindestens ein Icon ausblende. Ich denke aber, es sollte auch möglich sein, keine Icons auszublenden und somit alle Funktionen zu nutzen.

Contao-Version: 4.9.31
flipbert-Version: 1.6.3

Weiterhin habe ich bemerkt, dass die englischen Übersetzungen nicht vorhanden sind und somit die Auswahl der Icons gar nicht möglich ist.

![2022-07-26 12-55-21](https://user-images.githubusercontent.com/3033160/180990207-493f84e3-0043-4861-90c2-d951b910d0ec.png)

VG, Nicole

**Comment by cmartin6** [comment]
Ich habe soeben die Version 1.6.4 released - können Sie es bitte mit der neuen Version versuchen?

**Comment by cmartin6** [comment]
In Version 1.6.5 sollte dies behoben sein.
